In [84]:
"""!pip install yfinance==0.1.67
!mamba install bs4==4.10.0 -y
!pip install nbformat==4.2.0"""

Collecting yfinance==0.1.67
  Downloading yfinance-0.1.67-py2.py3-none-any.whl (25 kB)
Requirement already satisfied: pandas>=0.24 in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from yfinance==0.1.67) (1.3.5)
Requirement already satisfied: numpy>=1.15 in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from yfinance==0.1.67) (1.21.6)
Requirement already satisfied: requests>=2.20 in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from yfinance==0.1.67) (2.29.0)
Requirement already satisfied: multitasking>=0.0.7 in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from yfinance==0.1.67) (0.0.11)
Requirement already satisfied: lxml>=4.5.1 in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from yfinance==0.1.67) (4.9.2)
Requirement already satisfied: python-dateutil>=2.7.3 in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from pandas>=0.24->yfinance==0.1.67) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from pandas>=0.24->yfinance==0.1.67) (2023.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from requests>=2.20->yfinance==0.1.67) (3.1.0)
Requirement already satisfied: idna<4,>=2.5 in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from requests>=2.20->yfinance==0.1.67) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from requests>=2.20->yfinance==0.1.67) (1.26.15)
Requirement already satisfied: certifi>=2017.4.17 in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from requests>=2.20->yfinance==0.1.67) (2023.5.7)
Requirement already satisfied: six>=1.5 in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from python-dateutil>=2.7.3->pandas>=0.24->yfinance==0.1.67) (1.16.0)
Installing collected packages: yfinance
  Attempting uninstall: yfinance
    Found existing installation: yfinance 0.2.4
    Uninstalling yfinance-0.2.4:
      Successfully uninstalled yfinance-0.2.4
Successfully installed yfinance-0.1.67

                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (1.4.2) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████


Looking for: ['bs4==4.10.0']

[+] 0.0s
[+] 0.1s
pkgs/main/linux-64 ━━━━━━━━━╸━━━━━━━━━━━━━━━   0.0 B /  ??.?MB @  ??.?MB/s  0.1s
pkgs/main/noarch   ━━━━━━━━━━━━━━╸━━━━━━━━━━   0.0 B /  ??.?MB @  ??.?MB/s  0.1s
pkgs/r/linux-64    ━━━━━━━━━╸━━━━━━━━━━━━━━━   0.0 B /  ??.?MB @  ??.?MB/s  0.1s
pkgs/r/noarch      ━━━━━━━━━━╸━━━━━━━━━━━━━━   0.0 B /  ??.?MB @  ??.?MB/s  0.1s[+] 0.2s
pkgs/main/linux-64 ━━━━━━━━━━━━╸━━━━━━━━━━━━   0.0 B /  ??.?MB @  ??.?MB/s  0.2s
pkgs/main/noarch   ━━━━━━━━━╸━━━━━━━━━━━━━━━   0.0 B /  ??.?MB @  ??.?MB/s  0.2s
pkgs/r/linux-64    ━━━━━━━━━━━╸━━━━━━━━━━━━━   0.0 B /  ??.?MB @  ??.?MB/s  0.2s
pkgs/r/noarch      ━━━━━━━━━━━━━╸━━━━━━━━━━━  28.7kB /  ??.?MB @ 183.4kB/s  0.2s[+] 0.3s
pkgs/main/linux-64 ━━━━━━━━━━━━━━╸━━━━━━━━━━ 217.1kB /  ??.?MB @ 843.5kB/s  0.3s
pkgs/main/noarch   ━━━━━━━━━━━╸━━━━━━━━━━━━━ 376.8kB /  ??.?MB @   1.5MB/s  0.3s
pkgs/r/linux-64    ━━━━━━━━━━━━━━╸━━━━━━━━━━ 491.5kB /  ??.?MB @   1.9MB/s  0.3s
pkgs/r/noarch      ━━━━━━━━━━━━━━━╸━━━━━━━━━ 491.5kB /  ??.?MB @   1.9MB/s  0.3spkgs/main/noarch                                   853.5kB @   2.3MB/s  0.4s
[+] 0.4s
pkgs/main/linux-64 ╸━━━━━━━━━━━━━━━╸━━━━━━━━ 634.9kB /  ??.?MB @   1.8MB/s  0.4s
pkgs/r/linux-64    ╸━━━━━━━━━━━━━━━╸━━━━━━━━ 913.4kB /  ??.?MB @   2.6MB/s  0.4s
pkgs/r/noarch      ━╸━━━━━━━━━━━━━━━╸━━━━━━━ 938.0kB /  ??.?MB @   2.6MB/s  0.4s[+] 0.5s
pkgs/main/linux-64 ━━━╸━━━━━━━━━━━━━━━╸━━━━━   1.2MB /  ??.?MB @   2.6MB/s  0.5s
pkgs/r/linux-64    ━━━╸━━━━━━━━━━━━━━━╸━━━━━   1.3MB /  ??.?MB @   3.0MB/s  0.5s
pkgs/r/noarch      ━━━━╸━━━━━━━━━━━━━━━╸━━━━   1.3MB /  ??.?MB @   2.8MB/s  0.5s[+] 0.6s
pkgs/main/linux-64 ━━━━━╸━━━━━━━━━━━━━━━╸━━   1.7MB @   3.0MB/s             0.6s
pkgs/r/linux-64    ━━━━━━━━━━━━━━━━━━━━━━━━   1.9MB @   3.3MB/s Finalizing  0.6s
pkgs/r/noarch      ━━━━━╸━━━━━━━━━━━━━━━╸━━   1.7MB @   3.1MB/s             0.6spkgs/r/linux-64                                    @   3.3MB/s  0.6s
[+] 0.7s
pkgs/main/linux-64 ━━━━━━━━╸━━━━━━━━━━━━━━━━   2.2MB /  ??.?MB @   3.4MB/s  0.7s
pkgs/r/noarch      ━━━━━━━━━╸━━━━━━━━━━━━━━━   2.2MB /  ??.?MB @   3.3MB/s  0.7spkgs/r/noarch                                        2.3MB @   3.4MB/s  0.7s
[+] 0.8s
pkgs/main/linux-64 ━━━━━━━━━━╸━━━━━━━━━━━━━━   2.8MB /  ??.?MB @   3.6MB/s  0.8s[+] 0.9s
pkgs/main/linux-64 ━━━━━━━━━━━╸━━━━━━━━━━━━━   3.1MB /  ??.?MB @   3.6MB/s  0.9s[+] 1.0s
pkgs/main/linux-64 ━━━━━━━━━━━━━━╸━━━━━━━━━━   3.5MB /  ??.?MB @   3.7MB/s  1.0s[+] 1.1s
pkgs/main/linux-64 ━━━━━━━━╸━━━━━━━━━━━━━━━━   4.0MB /  ??.?MB @   3.8MB/s  1.1s[+] 1.2s
pkgs/main/linux-64 ━━━━━━━━━━╸━━━━━━━━━━━━━━   4.5MB /  ??.?MB @   3.9MB/s  1.2s[+] 1.3s
pkgs/main/linux-64 ━━━━━━━━━━━━━╸━━━━━━━━━━━   5.0MB /  ??.?MB @   4.0MB/s  1.3s[+] 1.4s
pkgs/main/linux-64 ━━━━━━━━━━━━━━━╸━━━━━━━━━   5.6MB /  ??.?MB @   4.1MB/s  1.4s[+] 1.5s
pkgs/main/linux-64 ━━╸━━━━━━━━━━━━━━━╸━━━━━━   6.0MB /  ??.?MB @   4.1MB/s  1.5s[+] 1.6s
pkgs/main/linux-64 ━━━━━━━━━━━━━━━━━━━━━━━━   6.4MB @   4.1MB/s Finalizing  1.6s[+] 1.7s
pkgs/main/linux-64                                 @   4.1MB/s  1.7s

Pinned packages:
  - python 3.7.*


Transaction

  Prefix: /home/jupyterlab/conda/envs/python

  Updating specs:

   - bs4==4.10.0
   - ca-certificates
   - certifi
   - openssl


  Package               Version  Build         Channel                 Size
─────────────────────────────────────────────────────────────────────────────
  Install:
─────────────────────────────────────────────────────────────────────────────

  + bs4                  4.10.0  hd3eb1b0_0    pkgs/main/noarch        10kB

  Upgrade:
─────────────────────────────────────────────────────────────────────────────

  - ca-certificates    2023.5.7  hbcca054_0    conda-forge
  + ca-certificates  2023.08.22  h06a4308_0    pkgs/main/linux-64     125kB
  - openssl              1.1.1t  h0b41bf4_0    conda-forge
  + openssl              1.1.1w  h7f8727e_0    pkgs/main/linux-64       4MB

  Downgrade:
─────────────────────────────────────────────────────────────────────────────

  - beautifulsoup4       4.11.1  pyha770c72_0  conda-forge
  + beautifulsoup4       4.10.0  pyh06a4308_0  pkgs/main/noarch        87kB

  Summary:

  Install: 1 packages
  Upgrade: 2 packages
  Downgrade: 1 packages

  Total download: 4MB

─────────────────────────────────────────────────────────────────────────────


[+] 0.0s
Downloading      ━━━━━━━━━━━━━━━━━━━━━━━   0.0 B                            0.0s
Extracting       ━━━━━━━━━━━━━━━━━━━━━━━       0                            0.0s[+] 0.1s
Downloading  (4) ━━━━━━━━━━━━━━━━━━━━━━━   0.0 B beautifulsoup4             0.0s
Extracting       ━━━━━━━━━━━━━━━━━━━━━━━       0                            0.0sbeautifulsoup4                                      86.6kB @ 593.1kB/s  0.1s
ca-certificates                                    125.5kB @ 799.6kB/s  0.2s
bs4                                                 10.2kB @  61.3kB/s  0.2s
[+] 0.2s
Downloading      ━━━━━━━━━━━━━━━━━━━━━━━   4.1MB                            0.1s
Extracting   (4) ━━━━━━━━━━━━╸━━━━━━━━━━       0 beautifulsoup4             0.0sopenssl                                              3.9MB @  21.1MB/s  0.2s
[+] 0.3s
Downloading      ━━━━━━━━━━━━━━━━━━━━━━━   4.1MB                            0.1s
Extracting   (4) ━━━━━━━━━━━━━╸━━━━━━━━━       0 beautifulsoup4             0.1s[+] 0.4s
Downloading      ━━━━━━━━━━━━━━━━━━━━━━━   4.1MB                            0.1s
Extracting   (4) ━━━━━━━━━━━━━━╸━━━━━━━━       0 beautifulsoup4             0.2s[+] 0.5s
Downloading      ━━━━━━━━━━━━━━━━━━━━━━━   4.1MB                            0.1s
Extracting   (4) ━━━━━━━━━━━━━━━╸━━━━━━━       0 beautifulsoup4             0.3s[+] 0.6s
Downloading      ━━━━━━━━━━━━━━━━━━━━━━━   4.1MB                            0.1s
Extracting   (4) ╸━━━━━━━━━━━━━━━╸━━━━━━       0 bs4                        0.4s[+] 0.7s
Downloading      ━━━━━━━━━━━━━━━━━━━━━━━   4.1MB                            0.1s
Extracting   (4) ━╸━━━━━━━━━━━━━━━╸━━━━━       0 bs4                        0.5s[+] 0.8s
Downloading      ━━━━━━━━━━━━━━━━━━━━━━━   4.1MB                            0.1s
Extracting   (4) ━━╸━━━━━━━━━━━━━━━╸━━━━       0 bs4                        0.6s[+] 0.9s
Downloading      ━━━━━━━━━━━━━━━━━━━━━━━   4.1MB                            0.1s
Extracting   (4) ━━━╸━━━━━━━━━━━━━━━╸━━━       0 bs4                        0.7s[+] 1.0s
Downloading      ━━━━━━━━━━━━━━━━━━━━━━━   4.1MB                            0.1s
Extracting   (4) ━━━━╸━━━━━━━━━━━━━━━╸━━       0 ca-certificates            0.8s[+] 1.1s
Downloading      ━━━━━━━━━━━━━━━━━━━━━━━   4.1MB                            0.1s
Extracting   (4) ━━━━━━╸━━━━━━━━━━━━━━━━       0 ca-certificates            0.9s[+] 1.2s
Downloading      ━━━━━━━━━━━━━━━━━━━━━━━   4.1MB                            0.1s
Extracting   (4) ━━━━━━━╸━━━━━━━━━━━━━━━       0 ca-certificates            1.0s[+] 1.3s
Downloading      ━━━━━━━━━━━━━━━━━━━━━━━   4.1MB                            0.1s
Extracting   (4) ━━━━━━━━╸━━━━━━━━━━━━━━       0 ca-certificates            1.1s[+] 1.4s
Downloading      ━━━━━━━━━━━━━━━━━━━━━━━   4.1MB                            0.1s
Extracting   (4) ━━━━━━━━━╸━━━━━━━━━━━━━       0 openssl                    1.2s[+] 1.5s
Downloading      ━━━━━━━━━━━━━━━━━━━━━━━   4.1MB                            0.1s
Extracting   (4) ━━━━━━━━━━╸━━━━━━━━━━━━       0 openssl                    1.3s[+] 1.6s
Downloading      ━━━━━━━━━━━━━━━━━━━━━━━   4.1MB                            0.1s
Extracting   (4) ━━━━━━━━━━━╸━━━━━━━━━━━       0 openssl                    1.4s[+] 1.7s
Downloading      ━━━━━━━━━━━━━━━━━━━━━━━   4.1MB                            0.1s
Extracting   (4) ━━━━━━━━━━━━╸━━━━━━━━━━       0 openssl                    1.5s[+] 1.8s
Downloading      ━━━━━━━━━━━━━━━━━━━━━━━   4.1MB                            0.1s
Extracting   (4) ━━━━━━━╸━━━━━━━━━━━━━━━       0 beautifulsoup4             1.6s[+] 1.9s
Downloading      ━━━━━━━━━━━━━━━━━━━━━━━   4.1MB                            0.1s
Extracting   (4) ━━━━━━━━╸━━━━━━━━━━━━━━       0 beautifulsoup4             1.7s[+] 2.0s
Downloading      ━━━━━━━━━━━━━━━━━━━━━━━   4.1MB                            0.1s
Extracting   (4) ━━━━━━━━━╸━━━━━━━━━━━━━       0 beautifulsoup4             1.8s[+] 2.1s
Downloading      ━━━━━━━━━━━━━━━━━━━━━━━   4.1MB                            0.1s
Extracting   (4) ━━━━━━━━━━━╸━━━━━━━━━━━       0 beautifulsoup4             1.9s[+] 2.2s
Downloading      ━━━━━━━━━━━━━━━━━━━━━━━   4.1MB                            0.1s
Extracting   (4) ━━━━━━━━━━━━╸━━━━━━━━━━       0 bs4                        2.0s[+] 2.3s
Downloading      ━━━━━━━━━━━━━━━━━━━━━━━   4.1MB                            0.1s
Extracting   (3) ━━━━╸━━━━━━━━━━━━━━━━━━       1 bs4                        2.1s[+] 2.4s
Downloading      ━━━━━━━━━━━━━━━━━━━━━━━   4.1MB                            0.1s
Extracting   (2) ━━━━━━━━━━╸━━━━━━━━━━━━       2 ca-certificates            2.2s[+] 2.5s
Downloading      ━━━━━━━━━━━━━━━━━━━━━━━   4.1MB                            0.1s
Extracting       ━━━━━━━━━━━━━━━━━━━━━━━       4                            2.3s
Downloading and Extracting Packages

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Collecting nbformat==4.2.0
  Downloading nbformat-4.2.0-py2.py3-none-any.whl (153 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 153.3/153.3 kB 14.4 MB/s eta 0:00:00
Requirement already satisfied: ipython-genutils in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from nbformat==4.2.0) (0.2.0)
Requirement already satisfied: jsonschema!=2.5.0,>=2.4 in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from nbformat==4.2.0) (4.17.3)
Requirement already satisfied: jupyter-core in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from nbformat==4.2.0) (4.12.0)
Requirement already satisfied: traitlets>=4.1 in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from nbformat==4.2.0) (5.9.0)
Requirement already satisfied: attrs>=17.4.0 in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat==4.2.0) (23.1.0)
Requirement already satisfied: importlib-metadata in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat==4.2.0) (4.11.4)
Requirement already satisfied: importlib-resources>=1.4.0 in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat==4.2.0) (5.12.0)
Requirement already satisfied: pkgutil-resolve-name>=1.3.10 in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat==4.2.0) (1.3.10)
Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat==4.2.0) (0.19.3)
Requirement already satisfied: typing-extensions in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat==4.2.0) (4.5.0)
Requirement already satisfied: zipp>=3.1.0 in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from importlib-resources>=1.4.0->jsonschema!=2.5.0,>=2.4->nbformat==4.2.0) (3.15.0)
Installing collected packages: nbformat
  Attempting uninstall: nbformat
    Found existing installation: nbformat 5.8.0
    Uninstalling nbformat-5.8.0:
      Successfully uninstalled nbformat-5.8.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
jupyter-server 1.24.0 requires nbformat>=5.2.0, but you have nbformat 4.2.0 which is incompatible.
nbclient 0.7.4 requires nbformat>=5.1, but you have nbformat 4.2.0 which is incompatible.
nbconvert 7.4.0 requires nbformat>=5.1, but you have nbformat 4.2.0 which is incompatible.
Successfully installed nbformat-4.2.0

In [85]:
import yfinance as yf
import pandas as pd
import requests
from bs4 import BeautifulSoup
import plotly.graph_objects as go
from plotly.subplots import make_subplots
from dateutil.parser import parse
from datetime import datetime
print("imported")

In [86]:
import warnings
# Ignore all warnings
warnings.filterwarnings("ignore", category=FutureWarning)

In [87]:
def make_graph(stock_data, ta, stock):
    fig = make_subplots(rows=2, cols=1, shared_xaxes=True, subplot_titles=("Historical Share Price", "Historical Revenue"), vertical_spacing = .3)
    stock_data_specific = stock_data[stock_data.Date <= pd.to_datetime('2021--06-14')]
    revenue_data_specific = revenue_data[datetime.strptime(str(revenue_data.Date),"%Y") <= pd.to_datetime('2021-04-30').year]
    fig.add_trace(go.Scatter(x=pd.to_datetime(stock_data_specific.Date, infer_datetime_format=True), y=stock_data_specific.Close.astype("float"), name="Share Price"), row=1, col=1)
    fig.add_trace(go.Scatter(x=pd.to_datetime(revenue_data_specific.Date, infer_datetime_format=True), y=revenue_data_specific.Revenue.astype("float"), name="Revenue"), row=2, col=1)
    fig.update_xaxes(title_text="Date", row=1, col=1)
    fig.update_xaxes(title_text="Date", row=2, col=1)
    fig.update_yaxes(title_text="Price ($US)", row=1, col=1)
    fig.update_yaxes(title_text="Revenue ($US Millions)", row=2, col=1)
    fig.update_layout(showlegend=False,
    height=900,
    title=stock,
    xaxis_rangeslider_visible=True)
    fig.show()

In [88]:
x=2023
y=str(x)
type(datetime.strptime(y,"%Y").year)

int

In [89]:
n=pd.to_datetime('2021-04-30').year
type(n)

int

In [ ]:
Question 1: Use yfinance to Extract Stock Data

In [90]:
ticker=yf.Ticker("TSLA")
tesla_data=ticker.history(period="max")
tesla_data

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2010-06-29 00:00:00-04:00,1.266667,1.666667,1.169333,1.592667,281494500,0.0,0.0
2010-06-30 00:00:00-04:00,1.719333,2.028000,1.553333,1.588667,257806500,0.0,0.0
2010-07-01 00:00:00-04:00,1.666667,1.728000,1.351333,1.464000,123282000,0.0,0.0
2010-07-02 00:00:00-04:00,1.533333,1.540000,1.247333,1.280000,77097000,0.0,0.0
2010-07-06 00:00:00-04:00,1.333333,1.333333,1.055333,1.074000,103003500,0.0,0.0
...,...,...,...,...,...,...,...
2023-11-20 00:00:00-05:00,234.039993,237.100006,231.020004,235.600006,116320100,0.0,0.0
2023-11-21 00:00:00-05:00,235.039993,243.619995,233.339996,241.199997,122288000,0.0,0.0
2023-11-22 00:00:00-05:00,242.039993,244.009995,231.399994,234.210007,117950600,0.0,0.0
2023-11-24 00:00:00-05:00,233.750000,238.750000,232.330002,235.449997,65125200,0.0,0.0
2023-11-27 00:00:00-05:00,236.889999,238.330002,232.100006,236.080002,111154533,0.0,0.0

In [91]:
ticker=yf.Ticker("TSLA")
tesla_data=ticker.history(period="max")
tesla_data.reset_index(inplace=True)
tesla_data

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits
0,2010-06-29 00:00:00-04:00,1.266667,1.666667,1.169333,1.592667,281494500,0.0,0.0
1,2010-06-30 00:00:00-04:00,1.719333,2.028000,1.553333,1.588667,257806500,0.0,0.0
2,2010-07-01 00:00:00-04:00,1.666667,1.728000,1.351333,1.464000,123282000,0.0,0.0
3,2010-07-02 00:00:00-04:00,1.533333,1.540000,1.247333,1.280000,77097000,0.0,0.0
4,2010-07-06 00:00:00-04:00,1.333333,1.333333,1.055333,1.074000,103003500,0.0,0.0
...,...,...,...,...,...,...,...,...
3372,2023-11-20 00:00:00-05:00,234.039993,237.100006,231.020004,235.600006,116320100,0.0,0.0
3373,2023-11-21 00:00:00-05:00,235.039993,243.619995,233.339996,241.199997,122288000,0.0,0.0
3374,2023-11-22 00:00:00-05:00,242.039993,244.009995,231.399994,234.210007,117950600,0.0,0.0
3375,2023-11-24 00:00:00-05:00,233.750000,238.750000,232.330002,235.449997,65125200,0.0,0.0
3376,2023-11-27 00:00:00-05:00,236.889999,238.330002,232.100006,236.080002,111154533,0.0,0.0

In [92]:
tesla_data.reset_index(inplace=True)
tesla_data.head(5)

,index,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits
0,0,2010-06-29 00:00:00-04:00,1.266667,1.666667,1.169333,1.592667,281494500,0.0,0.0
1,1,2010-06-30 00:00:00-04:00,1.719333,2.028000,1.553333,1.588667,257806500,0.0,0.0
2,2,2010-07-01 00:00:00-04:00,1.666667,1.728000,1.351333,1.464000,123282000,0.0,0.0
3,3,2010-07-02 00:00:00-04:00,1.533333,1.540000,1.247333,1.280000,77097000,0.0,0.0
4,4,2010-07-06 00:00:00-04:00,1.333333,1.333333,1.055333,1.074000,103003500,0.0,0.0

In [ ]:
Question 2: Use Webscraping to Extract Tesla Revenue Data

In [96]:
url="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0220EN-SkillsNetwork/labs/project/revenue.htm"
html_data=requests.get(url).text
soup=BeautifulSoup(html_data,"html5lib")
# create a dataframe for tesla 
tesla_revenue=pd.DataFrame(columns=['Data',"Revenue"])


for row in soup.find_all("tbody")[1].find_all("tr"):
    col = row.find_all("td")
    Date=col[0].text
    Revenue=col[1].text
    #append a row to the dataframe 
    tesla_revenue.append({"Data":Date,"Revenue":Revenue},ignore_index=True)
tesla_revenue.head()

Empty DataFrame
Columns: [Data, Revenue]
Index: []

In [97]:
soup=BeautifulSoup(html_data,"html5lib")

In [98]:
soup.find_all("tbody")[1]

<tbody>


				<tr>
					<td style="text-align:center">2022-09-30</td>





						<td style="text-align:center">$21,454</td>



				  </tr>


				<tr>
					<td style="text-align:center">2022-06-30</td>





						<td style="text-align:center">$16,934</td>



				  </tr>


				<tr>
					<td style="text-align:center">2022-03-31</td>





						<td style="text-align:center">$18,756</td>



				  </tr>


				<tr>
					<td style="text-align:center">2021-12-31</td>





						<td style="text-align:center">$17,719</td>



				  </tr>


				<tr>
					<td style="text-align:center">2021-09-30</td>





						<td style="text-align:center">$13,757</td>



				  </tr>


				<tr>
					<td style="text-align:center">2021-06-30</td>





						<td style="text-align:center">$11,958</td>



				  </tr>


				<tr>
					<td style="text-align:center">2021-03-31</td>





						<td style="text-align:center">$10,389</td>



				  </tr>


				<tr>
					<td style="text-align:center">2020-12-31</td>





						<td style="text-align:center">$10,744</td>



				  </tr>


				<tr>
					<td style="text-align:center">2020-09-30</td>





						<td style="text-align:center">$8,771</td>



				  </tr>


				<tr>
					<td style="text-align:center">2020-06-30</td>





						<td style="text-align:center">$6,036</td>



				  </tr>


				<tr>
					<td style="text-align:center">2020-03-31</td>





						<td style="text-align:center">$5,985</td>



				  </tr>


				<tr>
					<td style="text-align:center">2019-12-31</td>





						<td style="text-align:center">$7,384</td>



				  </tr>


				<tr>
					<td style="text-align:center">2019-09-30</td>





						<td style="text-align:center">$6,303</td>



				  </tr>


				<tr>
					<td style="text-align:center">2019-06-30</td>





						<td style="text-align:center">$6,350</td>



				  </tr>


				<tr>
					<td style="text-align:center">2019-03-31</td>





						<td style="text-align:center">$4,541</td>



				  </tr>


				<tr>
					<td style="text-align:center">2018-12-31</td>





						<td style="text-align:center">$7,226</td>



				  </tr>


				<tr>
					<td style="text-align:center">2018-09-30</td>





						<td style="text-align:center">$6,824</td>



				  </tr>


				<tr>
					<td style="text-align:center">2018-06-30</td>





						<td style="text-align:center">$4,002</td>



				  </tr>


				<tr>
					<td style="text-align:center">2018-03-31</td>





						<td style="text-align:center">$3,409</td>



				  </tr>


				<tr>
					<td style="text-align:center">2017-12-31</td>





						<td style="text-align:center">$3,288</td>



				  </tr>


				<tr>
					<td style="text-align:center">2017-09-30</td>





						<td style="text-align:center">$2,985</td>



				  </tr>


				<tr>
					<td style="text-align:center">2017-06-30</td>





						<td style="text-align:center">$2,790</td>



				  </tr>


				<tr>
					<td style="text-align:center">2017-03-31</td>





						<td style="text-align:center">$2,696</td>



				  </tr>


				<tr>
					<td style="text-align:center">2016-12-31</td>





						<td style="text-align:center">$2,285</td>



				  </tr>


				<tr>
					<td style="text-align:center">2016-09-30</td>





						<td style="text-align:center">$2,298</td>



				  </tr>


				<tr>
					<td style="text-align:center">2016-06-30</td>





						<td style="text-align:center">$1,270</td>



				  </tr>


				<tr>
					<td style="text-align:center">2016-03-31</td>





						<td style="text-align:center">$1,147</td>



				  </tr>


				<tr>
					<td style="text-align:center">2015-12-31</td>





						<td style="text-align:center">$1,214</td>



				  </tr>


				<tr>
					<td style="text-align:center">2015-09-30</td>





						<td style="text-align:center">$937</td>



				  </tr>


				<tr>
					<td style="text-align:center">2015-06-30</td>





						<td style="text-align:center">$955</td>



				  </tr>


				<tr>
					<td style="text-align:center">2015-03-31</td>





						<td style="text-align:center">$940</td>



				  </tr>


				<tr>
					<td style="text-align:center">2014-12-31</td>





						<td style="text-align:center">$957</td>



				  </tr>


				<tr>
					<td style="text-align:center">2014-09-30</td>





						<td style="text-align:center">$852</td>



				  </tr>


				<tr>
					<td style="text-align:center">2014-06-30</td>





						<td style="text-align:center">$769</td>



				  </tr>


				<tr>
					<td style="text-align:center">2014-03-31</td>





						<td style="text-align:center">$621</td>



				  </tr>


				<tr>
					<td style="text-align:center">2013-12-31</td>





						<td style="text-align:center">$615</td>



				  </tr>


				<tr>
					<td style="text-align:center">2013-09-30</td>





						<td style="text-align:center">$431</td>



				  </tr>


				<tr>
					<td style="text-align:center">2013-06-30</td>





						<td style="text-align:center">$405</td>



				  </tr>


				<tr>
					<td style="text-align:center">2013-03-31</td>





						<td style="text-align:center">$562</td>



				  </tr>


				<tr>
					<td style="text-align:center">2012-12-31</td>





						<td style="text-align:center">$306</td>



				  </tr>


				<tr>
					<td style="text-align:center">2012-09-30</td>





						<td style="text-align:center">$50</td>



				  </tr>


				<tr>
					<td style="text-align:center">2012-06-30</td>





						<td style="text-align:center">$27</td>



				  </tr>


				<tr>
					<td style="text-align:center">2012-03-31</td>





						<td style="text-align:center">$30</td>



				  </tr>


				<tr>
					<td style="text-align:center">2011-12-31</td>





						<td style="text-align:center">$39</td>



				  </tr>


				<tr>
					<td style="text-align:center">2011-09-30</td>





						<td style="text-align:center">$58</td>



				  </tr>


				<tr>
					<td style="text-align:center">2011-06-30</td>





						<td style="text-align:center">$58</td>



				  </tr>


				<tr>
					<td style="text-align:center">2011-03-31</td>





						<td style="text-align:center">$49</td>



				  </tr>


				<tr>
					<td style="text-align:center">2010-12-31</td>





						<td style="text-align:center">$36</td>



				  </tr>


				<tr>
					<td style="text-align:center">2010-09-30</td>





						<td style="text-align:center">$31</td>



				  </tr>


				<tr>
					<td style="text-align:center">2010-06-30</td>





						<td style="text-align:center">$28</td>



				  </tr>


				<tr>
					<td style="text-align:center">2010-03-31</td>





						<td style="text-align:center">$21</td>



				  </tr>


				<tr>
					<td style="text-align:center">2009-12-31</td>





						<td style="text-align:center"></td>



				  </tr>


				<tr>
					<td style="text-align:center">2009-09-30</td>





						<td style="text-align:center">$46</td>



				  </tr>


				<tr>
					<td style="text-align:center">2009-06-30</td>





						<td style="text-align:center">$27</td>



				  </tr>


				</tbody>

In [99]:
tables_list=pd.read_html(str(html_data))
tesla_data2=pd.DataFrame(tables_list[0])
tesla_data2.columns=["Date","Revenue"]
tesla_revenue=tesla_data2
tesla_revenue

    Date  Revenue
0   2021  $53,823
1   2020  $31,536
2   2019  $24,578
3   2018  $21,461
4   2017  $11,759
5   2016   $7,000
6   2015   $4,046
7   2014   $3,198
8   2013   $2,013
9   2012     $413
10  2011     $204
11  2010     $117
12  2009     $112

In [100]:
tesla_revenue["Revenue"] = tesla_revenue['Revenue'].str.replace(',|\$',"")
#tesla_revenue['Date']=tesla_revenue['Date'].to_pydatetime()
#for  date in tesla_revenue['Date']:
 #  date=date.to_pydatetime()
tesla_revenue

    Date Revenue
0   2021   53823
1   2020   31536
2   2019   24578
3   2018   21461
4   2017   11759
5   2016    7000
6   2015    4046
7   2014    3198
8   2013    2013
9   2012     413
10  2011     204
11  2010     117
12  2009     112

In [101]:
tesla_revenue.dropna(inplace=True)

tesla_revenue = tesla_revenue[tesla_revenue['Revenue'] != ""]
tesla_revenue.shape

(13, 2)

In [102]:
tesla_revenue.tail()

    Date Revenue
8   2013    2013
9   2012     413
10  2011     204
11  2010     117
12  2009     112

In [ ]:
Question 3: Use yfinance to Extract Stock Data

In [104]:
gme = yf.Ticker("GME")
gme_data = gme.history(period = 'max')
gme_data.head()

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2002-02-13 00:00:00-05:00,1.620129,1.693350,1.603296,1.691667,76216000,0.0,0.0
2002-02-14 00:00:00-05:00,1.712707,1.716074,1.670626,1.683250,11021600,0.0,0.0
2002-02-15 00:00:00-05:00,1.683250,1.687458,1.658001,1.674834,8389600,0.0,0.0
2002-02-19 00:00:00-05:00,1.666418,1.666418,1.578047,1.607504,7410400,0.0,0.0
2002-02-20 00:00:00-05:00,1.615920,1.662210,1.603296,1.662210,6892800,0.0,0.0

In [105]:
gme_data.reset_index(inplace=True)
gme_data

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits
0,2002-02-13 00:00:00-05:00,1.620129,1.693350,1.603296,1.691667,76216000,0.0,0.0
1,2002-02-14 00:00:00-05:00,1.712707,1.716074,1.670626,1.683250,11021600,0.0,0.0
2,2002-02-15 00:00:00-05:00,1.683250,1.687458,1.658001,1.674834,8389600,0.0,0.0
3,2002-02-19 00:00:00-05:00,1.666418,1.666418,1.578047,1.607504,7410400,0.0,0.0
4,2002-02-20 00:00:00-05:00,1.615920,1.662210,1.603296,1.662210,6892800,0.0,0.0
...,...,...,...,...,...,...,...,...
5480,2023-11-20 00:00:00-05:00,13.000000,13.200000,12.800000,12.800000,2294900,0.0,0.0
5481,2023-11-21 00:00:00-05:00,12.650000,12.720000,12.260000,12.550000,3710100,0.0,0.0
5482,2023-11-22 00:00:00-05:00,12.560000,12.710000,12.190000,12.290000,2358800,0.0,0.0
5483,2023-11-24 00:00:00-05:00,12.220000,12.410000,12.180000,12.200000,1232500,0.0,0.0
5484,2023-11-27 00:00:00-05:00,12.180000,12.330000,11.890000,11.910000,3679809,0.0,0.0

In [45]:
Question 4: Use Webscraping to Extract GME Revenue Data

In [107]:
url = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0220EN-SkillsNetwork/labs/project/stock.html"
html_data = requests.get(url).text
soup=BeautifulSoup(html_data,'html5lib')
soup.find_all("tbody")[1]

<tbody>


				<tr>
					<td style="text-align:center">2020-04-30</td>





						<td style="text-align:center">$1,021</td>



				  </tr>


				<tr>
					<td style="text-align:center">2020-01-31</td>





						<td style="text-align:center">$2,194</td>



				  </tr>


				<tr>
					<td style="text-align:center">2019-10-31</td>





						<td style="text-align:center">$1,439</td>



				  </tr>


				<tr>
					<td style="text-align:center">2019-07-31</td>





						<td style="text-align:center">$1,286</td>



				  </tr>


				<tr>
					<td style="text-align:center">2019-04-30</td>





						<td style="text-align:center">$1,548</td>



				  </tr>


				<tr>
					<td style="text-align:center">2019-01-31</td>





						<td style="text-align:center">$3,063</td>



				  </tr>


				<tr>
					<td style="text-align:center">2018-10-31</td>





						<td style="text-align:center">$1,935</td>



				  </tr>


				<tr>
					<td style="text-align:center">2018-07-31</td>





						<td style="text-align:center">$1,501</td>



				  </tr>


				<tr>
					<td style="text-align:center">2018-04-30</td>





						<td style="text-align:center">$1,786</td>



				  </tr>


				<tr>
					<td style="text-align:center">2018-01-31</td>





						<td style="text-align:center">$2,825</td>



				  </tr>


				<tr>
					<td style="text-align:center">2017-10-31</td>





						<td style="text-align:center">$1,989</td>



				  </tr>


				<tr>
					<td style="text-align:center">2017-07-31</td>





						<td style="text-align:center">$1,688</td>



				  </tr>


				<tr>
					<td style="text-align:center">2017-04-30</td>





						<td style="text-align:center">$2,046</td>



				  </tr>


				<tr>
					<td style="text-align:center">2017-01-31</td>





						<td style="text-align:center">$2,403</td>



				  </tr>


				<tr>
					<td style="text-align:center">2016-10-31</td>





						<td style="text-align:center">$1,959</td>



				  </tr>


				<tr>
					<td style="text-align:center">2016-07-31</td>





						<td style="text-align:center">$1,632</td>



				  </tr>


				<tr>
					<td style="text-align:center">2016-04-30</td>





						<td style="text-align:center">$1,972</td>



				  </tr>


				<tr>
					<td style="text-align:center">2016-01-31</td>





						<td style="text-align:center">$3,525</td>



				  </tr>


				<tr>
					<td style="text-align:center">2015-10-31</td>





						<td style="text-align:center">$2,016</td>



				  </tr>


				<tr>
					<td style="text-align:center">2015-07-31</td>





						<td style="text-align:center">$1,762</td>



				  </tr>


				<tr>
					<td style="text-align:center">2015-04-30</td>





						<td style="text-align:center">$2,061</td>



				  </tr>


				<tr>
					<td style="text-align:center">2015-01-31</td>





						<td style="text-align:center">$3,476</td>



				  </tr>


				<tr>
					<td style="text-align:center">2014-10-31</td>





						<td style="text-align:center">$2,092</td>



				  </tr>


				<tr>
					<td style="text-align:center">2014-07-31</td>





						<td style="text-align:center">$1,731</td>



				  </tr>


				<tr>
					<td style="text-align:center">2014-04-30</td>





						<td style="text-align:center">$1,996</td>



				  </tr>


				<tr>
					<td style="text-align:center">2014-01-31</td>





						<td style="text-align:center">$3,684</td>



				  </tr>


				<tr>
					<td style="text-align:center">2013-10-31</td>





						<td style="text-align:center">$2,107</td>



				  </tr>


				<tr>
					<td style="text-align:center">2013-07-31</td>





						<td style="text-align:center">$1,384</td>



				  </tr>


				<tr>
					<td style="text-align:center">2013-04-30</td>





						<td style="text-align:center">$1,865</td>



				  </tr>


				<tr>
					<td style="text-align:center">2013-01-31</td>





						<td style="text-align:center">$3,562</td>



				  </tr>


				<tr>
					<td style="text-align:center">2012-10-31</td>





						<td style="text-align:center">$1,773</td>



				  </tr>


				<tr>
					<td style="text-align:center">2012-07-31</td>





						<td style="text-align:center">$1,550</td>



				  </tr>


				<tr>
					<td style="text-align:center">2012-04-30</td>





						<td style="text-align:center">$2,002</td>



				  </tr>


				<tr>
					<td style="text-align:center">2012-01-31</td>





						<td style="text-align:center">$3,579</td>



				  </tr>


				<tr>
					<td style="text-align:center">2011-10-31</td>





						<td style="text-align:center">$1,947</td>



				  </tr>


				<tr>
					<td style="text-align:center">2011-07-31</td>





						<td style="text-align:center">$1,744</td>



				  </tr>


				<tr>
					<td style="text-align:center">2011-04-30</td>





						<td style="text-align:center">$2,281</td>



				  </tr>


				<tr>
					<td style="text-align:center">2011-01-31</td>





						<td style="text-align:center">$3,693</td>



				  </tr>


				<tr>
					<td style="text-align:center">2010-10-31</td>





						<td style="text-align:center">$1,899</td>



				  </tr>


				<tr>
					<td style="text-align:center">2010-07-31</td>





						<td style="text-align:center">$1,799</td>



				  </tr>


				<tr>
					<td style="text-align:center">2010-04-30</td>





						<td style="text-align:center">$2,083</td>



				  </tr>


				<tr>
					<td style="text-align:center">2010-01-31</td>





						<td style="text-align:center">$3,524</td>



				  </tr>


				<tr>
					<td style="text-align:center">2009-10-31</td>





						<td style="text-align:center">$1,835</td>



				  </tr>


				<tr>
					<td style="text-align:center">2009-07-31</td>





						<td style="text-align:center">$1,739</td>



				  </tr>


				<tr>
					<td style="text-align:center">2009-04-30</td>





						<td style="text-align:center">$1,981</td>



				  </tr>


				<tr>
					<td style="text-align:center">2009-01-31</td>





						<td style="text-align:center">$3,492</td>



				  </tr>


				<tr>
					<td style="text-align:center">2008-10-31</td>





						<td style="text-align:center">$1,696</td>



				  </tr>


				<tr>
					<td style="text-align:center">2008-07-31</td>





						<td style="text-align:center">$1,804</td>



				  </tr>


				<tr>
					<td style="text-align:center">2008-04-30</td>





						<td style="text-align:center">$1,814</td>



				  </tr>


				<tr>
					<td style="text-align:center">2008-01-31</td>





						<td style="text-align:center">$2,866</td>



				  </tr>


				<tr>
					<td style="text-align:center">2007-10-31</td>





						<td style="text-align:center">$1,611</td>



				  </tr>


				<tr>
					<td style="text-align:center">2007-07-31</td>





						<td style="text-align:center">$1,338</td>



				  </tr>


				<tr>
					<td style="text-align:center">2007-04-30</td>





						<td style="text-align:center">$1,279</td>



				  </tr>


				<tr>
					<td style="text-align:center">2007-01-31</td>





						<td style="text-align:center">$2,304</td>



				  </tr>


				<tr>
					<td style="text-align:center">2006-10-31</td>





						<td style="text-align:center">$1,012</td>



				  </tr>


				<tr>
					<td style="text-align:center">2006-07-31</td>





						<td style="text-align:center">$963</td>



				  </tr>


				<tr>
					<td style="text-align:center">2006-04-30</td>





						<td style="text-align:center">$1,040</td>



				  </tr>


				<tr>
					<td style="text-align:center">2006-01-31</td>





						<td style="text-align:center">$1,667</td>



				  </tr>


				<tr>
					<td style="text-align:center">2005-10-31</td>





						<td style="text-align:center">$534</td>



				  </tr>


				<tr>
					<td style="text-align:center">2005-07-31</td>





						<td style="text-align:center">$416</td>



				  </tr>


				<tr>
					<td style="text-align:center">2005-04-30</td>





						<td style="text-align:center">$475</td>



				  </tr>


				<tr>
					<td style="text-align:center">2005-01-31</td>





						<td style="text-align:center">$709</td>



				  </tr>


				</tbody>

In [110]:
gme_revenue=pd.DataFrame(columns=["Date","Revenue"])
for row in soup.find_all("tbody")[1].find_all("tr"):
    cols=row.find_all("td")
    date=cols[0].text
    rev=cols[1].text
    #append the record 
    gme_revenue.append({"Date":date,"Revenue":rev},ignore_index=True)
gme_revenue

Empty DataFrame
Columns: [Date, Revenue]
Index: []

In [115]:
my_list=pd.read_html(url)
gme_revenue=pd.DataFrame(my_list[1])
gme_revenue.columns=["Date","Revenue"]

In [116]:
gme_revenue.tail()

          Date Revenue
57  2006-01-31  $1,667
58  2005-10-31    $534
59  2005-07-31    $416
60  2005-04-30    $475
61  2005-01-31    $709

In [117]:
type(gme_revenue['Date'][1])

str

In [ ]:
Question 5: Plot Tesla Stock Graph

In [118]:
make_graph(tesla_data, tesla_revenue, 'Tesla')

TypeError: Invalid comparison between dtype=datetime64[ns, America/New_York] and Timestamp

In [ ]:
Question 6: Plot GameStop Stock Graph

In [120]:
make_graph(gme_data, gme_revenue, 'GameStop')

TypeError: Invalid comparison between dtype=datetime64[ns, America/New_York] and Timestamp